### ISSUE TITLE
Pulizia codice e Miglioramento dei Test

### ISSUE THREAD

**Issue by emaiannone** [gps-is-2019/amigo#27]
Testing:
Siamo risaliti alla causa principale degli errori di ieri sera, e cioè:

- In Documento mancava un Cascade
- In User c'era un metodo int getId() che oscurava quello di lombok

Adesso restano solo 6 failure nelle seguenti classi:
- TaskServiceImplIT
- GruppoControllerIT

E' bene che gli autori di queste classi li fixino.

Alcuni consigli

- I test unitari, usando dei DAO mockati, non scrivono sul DB, quindi gli ID degli oggetti vanno settati manualmente con setId()
- I test IT, usando i DAO effettivi, scrivono nel DB, e quando scrivono, gli ID diventano disponibili dalla volta successiva in cui si va a recuperare un oggetto tramite il DAO. Quindi non bisogna settarli prima della save(), altrimenti potrebbe dare problemi.
- Se un oggetto di classe A ha un riferimento ad un oggetto di classe B, e viene fatto A.setB(B), allora basta solo fare ADAO.save(), così da avere B automaticamente nel DB.

Forte di questi consigli, bisogna fixate gli altri casi di test (sono un po' difficili da leggere e con codice ridondante) ed aggiungerne di altri.

---------------------------------------------------

**Ecco le cose da fare in ordine di importanza**:

- [x] MVC: Risolvere issue di Manuel "Roba del Web Layer messa nel Service Layer"
- [x] Fix test della classe TaskServiceImplIT
- [x] Fix test della classe GruppoControllerIT
- [x] 'Optional.get()' without 'isPresent()' check. Risolvete il warning
- [x] Molti test hanno il warning "Redundant variable". Applicate il refactoring che vi propone IntelliJ, così il vostro codice si snellisce e diventa più leggibile.
- [x] Test dei metodi dei controller che fanno ricevono le POST
- [x] TaskControllerTest e TaskControllerIT fare i test uploadDocumentoTask e downloadDocumentoTask
- [x] GruppoControllerIT risolvere gli errori a runtime di tutti i test
- [x] GruppoControllerTest cos'è groupCandidatesList?
- [x] GruppoControllerTest cos'è nominaResposabile?
- [x] GruppoControllerTest cos'è removeMembroCommissione?
- [x] RepositoryControllerTest e RepositoryControllerIT vanno rifatti tutti
- [x] RepositoryServiceImplTest e RepositoryServiceImplIT fare il test downloadDocumento
- [x] ConsegnaControllerTest e ConsegnaControllerIT fare il test downloadDocumento
- [x] ConsegnaControllerTest e ConsegnaControllerIT findConsegneInviate aumentare il numero di TC
- [x] ConsegnaServiceImplIT fare il test sendDocumento
- [x] DocumentoServiceImplIT fare il test searchDocumenti
- [ ] Allineare i nomi dei test con il nome del metodo sotto test (ci sono dei casi in cui non c'è match)
- [ ] Allineare nome del provider con il metodo di test a cui fornisce gli input (ci sono dei casi in cui non c'è match)

Le seguenti riguardano il **Raggiungere 75% di Branch Coverage**. Consiglio: provate prima a vedere se è possibile togliere dei branch superflui nel codice sotto test (senza alterarne il comportamento, obv) e poi aumentare il numero di casi di test. 
- [x] Autenticazione
- [x] Documento
- [x] Gruppo
- [x] Repository
- [x] Task
- [ ] Consegna

Violazioni checkstyle:
- [x] Javadoc, revisionare tutto
- [x] Fare package-info.java
- [x] Fixare ultime violazioni checkstile
- [ ] Risolvere altri warning di IntelliJ
- [ ] Opzionale: Javadoc delle interfacce

**Comment by emaiannone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AI[62] - Pulizia codice e Incremento Test Case](https://trello.com/c/okVsJRoe/114-ai62-pulizia-codice-e-incremento-test-case)

**Comment by mdestefano** [comment]
Giusto una precisazione, il fatto che se A a riferimento a B e si fa A.setB(B) basta fare solo ADao.save(A) si verifica solo se su A, il riferimento a B è annotato con Cascade.ALL o Cascade.PERSIST
